version: "3.7"

services:
    # image project
    app:
        container_name: app-laravel
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        depends_on:
            - redis
        networks:
            - laravel

    # nginx
    nginx:
        image: nginx:alpine
        container_name: web-server
        restart: unless-stopped
        ports:
            - "80:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - laravel

    # db mysql
    db:
        image: mysql:8.0
        container_name: database
        platform: linux/amd64
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE:-laravel}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
            MYSQL_PASSWORD: ${DB_PASSWORD:-userpass}
            MYSQL_USER: ${DB_USERNAME:-username}
        volumes:
            - ./.docker/mysql/dbdata:/var/lib/mysql
        ports:
            - "3389:3306"
        networks:
            - laravel

    # redis
    redis:
        container_name: redis
        image: redis:latest
        networks:
            - laravel

    # redis
    mailpit:
      container_name: email-service
      image: axllent/mailpit
      restart: unless-stopped
      volumes:
        - ./data:/data
      ports:
        - 8025:8025
        - 1025:1025
      environment:
        MP_MAX_MESSAGES: 5000
        MP_DATABASE: /data/mailpit.db
        MP_SMTP_AUTH_ACCEPT_ANY: 1
        MP_SMTP_AUTH_ALLOW_INSECURE: 1

networks:
    laravel:
        driver: bridge
